### ISSUE TITLE
survey :: por dónde cruzas

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-garitacenter#20]
Los íconos no tiene posición cool (print-screen)
- Falta meter pedwest
- Estaría cool ver otay sin scroll (al menos una parte para que el usuario tenga más claro de que está la opción)

<img width="381" alt="screen shot 2016-09-06 at 5 39 16 pm" src="https://cloud.githubusercontent.com/assets/7799215/18293551/0b2d443c-7459-11e6-8078-b3667615a14f.png">

**Comment by ale-romo** [comment]
Listo
