### ISSUE TITLE
survey :: a qué altura

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-garitacenter#21]
El título no tiene el estilo del diseño (font blanco, y tamaño)

<img width="341" alt="screen shot 2016-09-06 at 5 42 21 pm" src="https://cloud.githubusercontent.com/assets/7799215/18293579/54ab421c-7459-11e6-8680-3f15d30ed6b7.png">

**Comment by ale-romo** [comment]
check
