### ISSUE TITLE
Header :: Cambiar de ciudad

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-garitacenter#41]
La idea es activar otras ciudades, para esto, considerando mobile first, se me ocurre poner el típo botón menú:
<img width="138" alt="screen shot 2016-12-18 at 5 52 48 pm" src="https://cloud.githubusercontent.com/assets/7799215/21297743/cd3a86c4-c54a-11e6-8593-cf4b8355dfc4.png">

En la parte superior derecha:

<img width="350" alt="screen shot 2016-12-18 at 5 53 06 pm" src="https://cloud.githubusercontent.com/assets/7799215/21297747/dd75ec5e-c54a-11e6-9d05-cf67ad928fb0.png">

La cura es que al presionar se mostrará de listado de otras ciudades.

de tu parte con que te avientes el diseño + maquetado, con eso, ya yo me encargo de activarlo,
chido!

**Comment by ale-romo** [comment]
Puedes armar los elementos para ya nomás estilizarlos yo?
