### ISSUE TITLE
Mainmenu :: Notificación

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-garitacenter#42]
Actualmente la sección de reporte de usuario solo la ve el 1% de los usuarios, la idea es de alguna forma hacer que sea más visitada, se me ocurre que a la derecha de 'reporte de usuario' poner el ícono de "notificación" estilo fb, dando el número de mensajes creados en los últimos 30 mins.

<img width="371" alt="screen shot 2016-12-18 at 5 56 07 pm" src="https://cloud.githubusercontent.com/assets/7799215/21297762/43b1490a-c54b-11e6-858d-c02a06376aff.png">

<img width="46" alt="screen shot 2016-12-18 at 5 35 54 pm" src="https://cloud.githubusercontent.com/assets/7799215/21297764/46da57c0-c54b-11e6-9d1a-8d2041164b1f.png">

Una vez que el usuario de click en 'reporte de usuario' entonces ya no mostraré la "notificación".

Esto genera otro reto, el hacer saber al usuario cuáles son los # mensajes nuevos generados en los últimos 30 mins, para esto se me ocurre poner en un fondo diferente aquellos msgs de hace menos 30 mins, junto con una explicación justo debajo del CTA explicando:
[azul] = Mensaje reportado hace menos de 30 mins

<img width="368" alt="screen shot 2016-12-18 at 6 01 01 pm" src="https://cloud.githubusercontent.com/assets/7799215/21297791/f4816698-c54b-11e6-9c91-8a5fa719759c.png">

Tu parte es diseño y maquetado, ya yo me encargo de activarlo, de igual forma tu input de cómo atacar esto, quizás tienes otra estrategía.

Cheers.

**Comment by ale-romo** [comment]
Hay forma de simular reportes en localhost?

**Comment by ale-romo** [comment]
Me parece innecesario gastar espacio explicando "X caracterización visual significa que un reporte tiene menos de 30 minutos" además de que el chiste de las cosas bien diseñadas es que se entiendan sin necesidad de explicaciones.

Como solucion propuesta hice una etiqueta de "reciente" y enfaticé la hora. Se pierde el entendido de los "30 minutos" pero no se me hace que sea información que tenga que ser necesariamente explicita.

**Comment by garciadiazjaime** [comment]
good call!
